version: "3.6"
services:
  app:
    container_name: ddev-${DDEV_SITENAME}-app
    build: app-build
    expose:
      - 6006
      - 4000
    command: "sleep infinity"
    volumes:
      - "../:/app"
      - ".:/mnt/ddev_config"
    working_dir: /app
    environment:
      APP_ENV: ddev
      VIRTUAL_HOST: $DDEV_HOSTNAME
      HTTP_EXPOSE: "80:4000,6006"
      HTTPS_EXPOSE: "443:4000"
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    networks: [ default, ddev_default ]
